modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory (28 is current forge version)
issueTrackerURL="https://github.com/lazyMods/Baubles/issues" #optional
[[mods]] #mandatory
modId="baubles" #mandatory
version="1.6.1" #mandatory
displayName="Baubles" #mandatory
logoFile="BLogo.png" #optional
credits="Azanor" #optional
authors="lazynessmind" #optional
description='''Adding a touch of bling to Minecraft'''